openbank:
  useCode : M202111920
  client-id: 318b30f8-87cc-4e10-aff2-027ebd3e3b3a
  client-secret: 5081186a-2d57-49cb-ab45-03dc853079b8
  access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIxMTAwNzcxMjYzIiwic2NvcGUiOlsiaW5xdWlyeSIsImxvZ2luIiwidHJhbnNmZXIiXSwiaXNzIjoiaHR0cHM6Ly93d3cub3BlbmJhbmtpbmcub3Iua3IiLCJleHAiOjE2MzcxNjY0ODksImp0aSI6IjhkMTk2YTIyLWRmMzYtNGM5Ny1hZTJlLTQzODBkMWUwZDI2OSJ9.m9HjX3543q699RM3lbeXZhmJUZqJTGDvbc8sOpdvJBc
